### ISSUE TITLE
Signed in user not recognised after loading guestlist via setEmailGuestlist API

### ISSUE THREAD

**Issue by phil-maynard** [gathertown/api-examples#1]
### Issue summary
I've been using the guest list feature to restrict access to a Gather space. This has been working great when loaded via CSV file. However, when I attempt to load the guest list via the setEmailGuestlist API, although the list looks correct within the Gather space dashboard, the logged in user [me] isn't recognised as being on the list.

### HTTP Post value
HTTP Post with the following body

```
{
  "apiKey": "aQ************nWEY",
  "spaceId": "I2s*********B\\Party",
  "overwrite": "True",
  "guestlist": "{\n \"philmaynard@************.org\":  {\n    \"role\" : \"admin\",\n    \"name\": \"Phil Maynard\",\n    \"affiliation\": \"***************\"\n  }\n}"
}
```

### Background
I'm using Microsoft Power Automate to get the members of a Microsoft 365 Group and add them to the Gather space guestlist. I'm generating a JSON object within the Power Automate flow based on the group membership and using this object within the HTTP Post.

I suspect that the JSON is miss-formatted or that I'm not referencing it correctly within the HTTP Post but I've tried a numebr of things with the same result - see images
![2021-01-14_17-52-01](https://user-images.githubusercontent.com/29703291/104629385-561e3900-5691-11eb-9aaa-e45a511e54cc.png)
![2021-01-14_17-49-36](https://user-images.githubusercontent.com/29703291/104629389-574f6600-5691-11eb-82de-7034be6d3772.png)
![2021-01-14_17-50-58](https://user-images.githubusercontent.com/29703291/104629388-56b6cf80-5691-11eb-80ac-c0660d2fc940.png)

### Postscript
Thanks for everything you and the team have done to make Gather.Town! It's an amazing space and I'm really looking forward to  promoting it more within my organisation. Thanks Again. Phil

**Comment by phil-maynard** [comment]
Sorry, I realised my mistake! I forgot to set the content type in the header to `Content-type: application/json; charset=utf-8`
This changed fixed my problem 😀
![2021-01-15_09-54-09](https://user-images.githubusercontent.com/29703291/104710597-2b2af800-5718-11eb-984e-cc4909d98b57.png)

**Comment by npfoss** [comment]
glad you sorted it out, sorry for the trouble!
